# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.9.3_7.2.0
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    env_file: .env
    volumes:
      - /data/wazuh/backup/:/var/ossec/backup
      - /data/wazuh/data/:/var/ossec/data
      - /data/wazuh/queue/:/var/ossec/queue
      - /data/wazuh/ruleset/:/var/ossec/ruleset
      - /data/wazuh/stats/:/var/ossec/stats
      - /data/wazuh/var/db:/var/ossec/var/db
      - /data/wazuh/var/download:/var/ossec/var/download
      - /data/wazuh/var/upgrade:/var/ossec/var/upgrade


  logstash:
#    Local logstash docker modification to enable syslog output plugin
#    image: docker.elastic.co/logstash/logstash:7.3.0
    image: logstash:latest
    hostname: wazuh-logstash
    command: --path.settings /etc/logstash -f /etc/logstash/conf.d
    restart: always
    volumes:
      - /data/logstash/config:/etc/logstash
      - /data/logstash/data:/usr/share/logstash/data
      - /data/logstash/logs:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
      - wazuh
    environment:
      - LS_HEAP_SIZE=2048m

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.3_7.2.0
    hostname: elasticsearch
    restart: always
    volumes:
      - /data/elasticsearch/config:/usr/share/elasticsearch/config
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    env_file: .env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.9.3_7.2.0
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    env_file: .env
  nginx:
    image: wazuh/wazuh-nginx:3.9.3_7.2.0
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana
    env_file: .env
